# Generated by Django 5.2.7 on 2025-10-27 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compañia', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('producto', models.CharField(max_length=100)),
                ('precios', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entregas', models.IntegerField(default=0)),
                ('licencia_permiso', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cuidados', models.TextField()),
                ('enfermedades', models.TextField(blank=True)),
                ('especie', models.CharField(max_length=50)),
                ('alimentacion', models.CharField(max_length=100)),
                ('foto_animal', models.ImageField(blank=True, null=True, upload_to='img_animales/')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='app_tienda.proveedor')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
            },
        ),
    ]
